package com.mml.hash;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class MyMD5_SHA1 {

	
	public static String encryption(String input) {
		try {
		MessageDigest md = MessageDigest.getInstance("SHA-1");
		
		// digest() method is called
        // to calculate message digest of the input string
        // returned as array of byte
        byte[] messageDigest = md.digest(input.getBytes());

        // Convert byte array into signum representation
        BigInteger no = new BigInteger(1, messageDigest);
        
        // Convert message digest into hex value
        String hashtext = no.toString(16);
        
     // Add preceding 0s to make it 32 bit
        while (hashtext.length() < 32) {
            hashtext = "0" + hashtext;
        }
        return hashtext;
        
	} catch (NoSuchAlgorithmException e) {
		// TODO Auto-generated catch block
		 throw new RuntimeException(e);
	}
		

	}
	
	
	public static void main(String[] args) {
		System.out.println("HashCode Generated by SHA-1 for: ");
		 
        String s1 = "Lets do encryption";
        System.out.println("\n" + s1 + " : " + encryption(s1));
 
        String s2 = "hello world";
        System.out.println("\n" + s2 + " : " + encryption(s2));
		
		
	}
}
